### ISSUE TITLE
Backspace in JS tab doesn't work

### ISSUE THREAD

**Issue by talentlessguy** [jsitor/jsitor#30]
![Screenshot_20190921-003511](https://user-images.githubusercontent.com/35937217/65360226-bfaa4680-dc07-11e9-8adf-f2a76243ea00.png)

I try to press Backspace and nothing happens

Although it works in other tabs

specs:

**Android** 6.0
**Device** BQS 5020

**Comment by ashvin777** [comment]
Strange, thanks for reporting this @talentlessguy . We will look into this.

**Comment by ashvin777** [comment]
Hi @talentlessguy ,  We have fixed some major issues in our app. Also, we have not observed the reported issue any more. Request you to download the latest build and verify the issue.

**Comment by talentlessguy** [comment]
@ashvin777 still doesn't work. It locks when erasing a keyword.

**Comment by ashvin777** [comment]
Hi @talentlessguy , Somehow I am not able to reproduce this in Android 6.0. Is it possible for you to share more details like steps and some recording?

**Comment by ashvin777** [comment]
Hi @talentlessguy , Please update to the latest version. The editor experience has been improved a lot, that should this problem as well.
